# version: "3.9" considéré comme obsolète d'après le terminal

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5177:5177"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5177 

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    command: npm run preview -- --host 0.0.0.0 --port 5173    